<?php
/**
 * Created by PhpStorm.
 * User: wugang
 * Date: 17/3/7
 * Time: 下午3:24
 */

namespace App\Http\Requests\Carrier;


use App\Models\CarrierPlayerGamePlatRebateFinancialFlow;
use Illuminate\Foundation\Http\FormRequest;

class UpdateCarrierPlayerLevelRebateFinancialFlowRequest extends FormRequest
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        \Validator::extend('validateFlowStepRateJson','App\Models\CarrierPlayerGamePlatRebateFinancialFlow@validateFlowStepRateJson');
        return CarrierPlayerGamePlatRebateFinancialFlow::$rules;
    }

    public function attributes()
    {
        return CarrierPlayerGamePlatRebateFinancialFlow::$requestAttributes; // TODO: Change the autogenerated stub
    }


}